from .start_command import *
from .help_command import *
from .view_dz_command import *
from .getid_command import *
from .count_command import *
from .random_member_command import *
from .chatinfo_command import *
from .user_full_info_command import *
from .myinfo_command import *
from .okak_command import *
from .set_verify_days import *
from .randomverify_command import *
from .set_chat import *
from .get_all_bot_chats import *
from config import *
from .botwifi import *
from .game import *
from .user_subscribed import *
from .abitur_command import *